name: Python_linter

on:
  push:
    paths:
      - "**/*.py"

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: pip install ruff

      - name: Check files for linting
        run: ruff check .
